### ISSUE TITLE
HAR

### ISSUE THREAD

**Issue by mariodeci** [vmi/selenese-runner-java#153]
is possible to introduce HAR (Http Archive) in output?
Or, alternatively, take the heavier loaded resource (get, post, css, js, ..) for each testcase?

Something like: "test case take 135seconds, heavier resouce is "http://.../js/myScripts.js" with 28seconds

**Comment by vmi** [comment]
It is not possible.

It is possible for selenese-runner-java to support features only within Selenium WebDriver API.
Selenium has no interface for getting the detail information of pages.

I recommend that you propose the idea to Selenium project.

**Comment by mariodeci** [comment]
I'm studying about it and I've found two solution:
*browserMob: cross browser, with a proxy, but with some problems (loading time, wui elements interaction problems);

* firebug+netexport: only for firefox, but with a simple FirefoxProfile with 2 xpi extension you can export/generate an har: it is a simple export of the net panel of firebug with a lot of information about single element request (and the total time).

Finally, with harlib library you can analize the exported har.

I'll try to integrate it in seleneserunner.

Hope this will help your project ;)

**Comment by neillfontes** [comment]
@mariodeci What kinda of enhancements do you propose?

I like very much the coupling of BrowserMod with Selenium as well. Since all the calls are proxied to browserMob, it would be easy to create tests for 

"This given js/css file is delaying more than expected"
"This test needs to fail if this XHR call is not performed properly"

Please drop me a message if you are interested.
