### ISSUE TITLE
Link locator optimization

### ISSUE THREAD

**Issue by wimpster** [vmi/selenese-runner-java#162]
We noticed high CPU usage in Chrome(driver) and traced it back to the current implementation of the _link locator_ as implemented in _LinkHandler.java_. It currently works like this:
* Retrieve all _a_ tags
* Iterate over them
* Retrieve their text value
* Match the text against a regular expression

For pages with a large amount of links it starts using quite an amount of CPU and slows down execution of test cases significantly.

**Comment by wimpster** [comment]
We rewrote the _LinkHandler_ implementation to use XPath, that fixed our problems. Implementation below. If you'd rather have a diff or PR, please let me know.

```java
     @Override
     public List<WebElement> handle(WebDriver driver, String arg) {
       // Convert the argument to an XPath
       String xpath = "//a[contains(text(),";

       if (arg.indexOf('\'') >= 0) {
         // Escape embedded single quotes by using concat()
         xpath += "concat('" + arg.replace( "'", "',\"'\",'" ) + "')";
       }
       else {
         xpath += "'" + arg + "'";
       }

       xpath += ")]";

       return driver.findElements(By.xpath(xpath));
     }
```

Thank you for selenese runner!

**Comment by vmi** [comment]
I'm thankful for your suggestion.
I optimized the handler for `link=glob:...` and `link=exact:...` based on a above code.
Please test it.

**Comment by vmi** [comment]
Can I close this ticket?

**Comment by AndreaColoru** [comment]
Hi, with the new released version 1.11.0 there are some issues locating anchor by link expecially when inside an anchor node there are nested nodes. The previous version worked fine for me in this case.

For example:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<root>
	<a href="link1">
		Close
	</a>
	<a href="link2">
		<span>Close</span>
	</a>
</root>
```
With the released code just link1 is found and link2 is not located.
In my opinion the problem seems to be in the usage of contains[text() instead of contains[.
Below 2 screenshots with the current results and the possibile new solution results

Thank you

![test1](https://cloud.githubusercontent.com/assets/10160743/9300807/0962b584-44ca-11e5-8de0-e6dc6aff7215.png)
![test2](https://cloud.githubusercontent.com/assets/10160743/9300811/0e58bce6-44ca-11e5-996f-6c95a1daa8c7.png)

**Comment by vmi** [comment]
Hi, AndreaColoru

Thanks for your suggestion.
I fixed.
Please test it.

**Comment by vmi** [comment]
Can I close this ticket?

**Comment by AndreaColoru** [comment]
Hi . I just tryed to launch your LinkHandlerTest with junit  and got this error.
Command#2: assertElementPresent("link=as*s")
org.openqa.selenium.InvalidSelectorException: The given selector //a[contains(.,"as")] and contains(.,"s")] is either invalid or does not result in a WebElement. The following error occurred:
InvalidSelectorError: Unable to locate an element with the xpath expression //a[contains(.,"as")] and contains(.,"s")] because of the following error:.......
Anyway  the exact search works with your link_handler.html test page but not for the web resource where i do test automation (I will indagate in future as I actually changed to xpath).
Cheers.

**Comment by vmi** [comment]
Thanks for your report and P.R.

**Comment by AndreaColoru** [comment]
Finally I Found the reason while in my test case  the link by exact string fails in selenese runner (but not in selenium ide): the reason is  spaces and /n or /r  before the term "Close" .
`<a href="link2">
        <span>
                     Close</span>
</a>`
A possible solution should be in this article: http://stackoverflow.com/questions/11776910/xpath-expression-to-remove-whitespace.
If I will have the necessary time I'll fix for you.
Thanks for selenese runner !!

**Comment by vmi** [comment]
I think above problem has been solved by P.R. #166.
